### ISSUE TITLE
Suggestion on ZendAcl->isGranted(string $role, ServerRequestInterface $request)

### ISSUE THREAD

**Issue by augusito** [zendframework/zend-expressive-authorization-acl#15]
Hey. I have a suggestion on the second argument of ZendAcl->isGranted(string $role, **ServerRequestInterface $request**). 
The argument can be revised to make it more open. 
This will allow the method to be used in various scenarios where we may not have **Psr\Http\Message\ServerRequestInterface** instance, but may still want to pass a resource as either a **sting** or as an instance of **Zend\Permissions\Acl\Resource\ResourceInterface**. 
One such scenario is where I may need to filter navigation items based on the permissions of a role and the resource is provided as a **string** or as an instance of **Zend\Permissions\Acl\Resource\ResourceInterface**. 
In this case, I don't need to have **Psr\Http\Message\ServerRequestInterface** instance or a **route name** for that matter.
I suggest revision on the method as follows:

	/**
     * Check if a role is granted for the resource
     *
     * @param string $role            
     * @param string|\Zend\Permissions\Acl\Resource\ResourceInterface|\Psr\Http\Message\ServerRequestInterface|null $resource            
     * @return bool
     */
    public function isGranted(string $role, $resource): bool
    {
        if (null === $resource 
            || is_string($resource) 
                || $resource instanceof ResourceInterface) {
            $this->resource = $resource;
        } elseif ($resource instanceof ServerRequestInterface) {
            $routeResult = $resource->getAttribute(RouteResult::class, false);
            if (false === $routeResult) {
                throw new Exception\RuntimeException(sprintf(
                    'The %s attribute is missing in the request; cannot perform ACL authorization checks', 
                    RouteResult::class
                    ));
            }
            $this->resource = $routeResult->getMatchedRouteName();
        } else {
            throw new Exception\InvalidArgumentException(sprintf(
                'Invalid argument: $resource must be null, a string, an instance of %, or an instance of %', 
                ResourceInterface::class, ServerRequestInterface::class
                ));
        }
        
        return $this->acl->isAllowed($role, $this->resource);
    }

PS, The revision does not break usage by **\Zend\Expressive\Authorization\AuthorizationMiddleware**

**Comment by ezimuel** [comment]
We cannot provide this change because the ACL adapter needs to implement an [AuthorizationInterface](https://github.com/zendframework/zend-expressive-authorization/blob/master/src/AuthorizationInterface.php) that requires `ServerRequestInterface`.

If you need, you can implement a custom class for the authorization, passing the dependecies in the constructor (with a [Factory Service](https://zendframework.github.io/zend-servicemanager/configuring-the-service-manager/#factories)) and use it inside the `isGranted(string $role, ServerRequestInterface $request)`function.
